### PR TITLE
Regtest infrastructure

### PR DESCRIPTION
**Pull request by eszterpos**
Removing some "flaky tests" from the branch where github has been behaving suspiciously. 
Running locally, the tests proved to be reliable in many different environments, while on github they passed or failed in an unpredictable manner. 
These tests are now stored for future reference in the regtest_with_flakytests branch. 

Namely,
GEOP/BFGS/zundel
GEOP/BGS-TRM/zundel
GEOP/CG/zundel
GEOP/CG/pswater

We will contact github about the issue, but for now I have removed them to have a reliable regtest infrastructure in place.
@litman90 can you please approve and merge this PR?

### CODE REVIEW

**Comment by mahrossi** [comment]
Eszter, this is amazing work (and Yair too). I will review this soon, but I believe you guys did a thorough job.

**Comment by venkatkapil24** [comment]
Fine by me. However, master py3 needs to be merged into master first.

**Comment by litman90** [comment]
@venkatkapil24, I see no point why we should merge master-py3 into master before merging this PR which is READY (reviewed by 3 person), and you haven't mentioned any specific reason more than stating that it is important. Am I missing something obvious Venkat?
Moreover, merging this PR first will allow us to detect if the other PR breaks some of the core functionalities. IMO the sooner we get the regtest in the main pipeline the better. 
@mahrossi, do you agree? i.e Should we merge first this PR and then review (and eventually merge) the PR #139?

**Comment by mahrossi** [comment]
It is all good guys, I updated, now rebasing this branch and I will just approve this one in a few minutes too.

**Review by litman90 — APPROVED** [review]

**Comment by litman90** [comment]
I checked and there is no need to make a rebase after the merge of the PR #139. I proceed to merge this PR.

**Comment by mahrossi** [comment]
Only because I had already rebased.

**Pull request merged**
