### PR TITLE
Fix nasty queueing bug

### PR DESCRIPTION
**Pull request by ceriottm**
@DavideTisi , try this branch, it should fix the PIMD problem

### CODE REVIEW

**Comment by mahrossi** [comment]
the order of the or condition matters?!?!?

**Comment by DavideTisi** [comment]
yes this is python magic ahaha
If the first condition is True, thus the whole `or` is `True` it does not evaluate the second

**Comment by ceriottm** [comment]
@DavideTisi  if you confirm that this works I would merge

**Comment by DavideTisi** [comment]
Yes yes it works, it scales as it should

**Pull request merged**
