### PR TITLE
Phonons bugfix

### PR DESCRIPTION
**Pull request by litman90**
Fixes a small bug in the printall function inside motion/phonons. 
A regression test was added for the fd_phonons functionality

### CODE REVIEW

**Review by venkatkapil24 — COMMENTED** [review]
Looks good to me. Is there anything else that you would like to do over here?

**Comment by litman90** [comment]
That is it for this PR.

**Comment by litman90** [comment]
all the checks pass now, so if you find it ok, please merge it.

**Review by venkatkapil24 — APPROVED** [review]
okay

**Pull request merged**
