### PR TITLE
Cayley friction schedule condition

### PR DESCRIPTION
**Pull request by korolrom**
I have added a new method to compute the minimum tau_k as per condition (37) in https://arxiv.org/pdf/1907.07941.pdf. I need some guidance on how to proceed with the second condition. In particular, what are the frequency units in i-Pi and is there a way to access the highest frequency of the system as well as set it to some default value? That would be max_freq that is currently commented out.

Ondrej, I hope you can help with that.

Thanks, Roman

### CODE REVIEW

**Comment by ceriottm** [comment]
Note that this should eventually be merged into master-py3 as master is now officially closed

**Comment by ceriottm** [comment]
@korolrom  can you update this PR to refer to the master-py3 branch? Otherwise I will close it and you can create a new one against the Py3 version.

**Comment by mahrossi** [comment]
Hello @korolrom -- this would be a good time to update the PR to the current master! Everything now is in py3 and this is a great implementation that should go there.

**Comment by mahrossi** [comment]
I will merge this to this korolm-master here. Then we can try to open a PR to current master. At least it does not get lost, but korolrom-master branch should be deleted from this repo ASAP.

**Comment by venkatkapil24** [comment]
What is the status here ?

**Comment by korolrom** [comment]
Hi, sorry for prolonged silence. I just saw this.

Basically, we believe this modification is no longer needed as per our recent efforts to find the optimal friction for internal modes in the context of the BCOCB propagator (see https://arxiv.org/abs/2011.01601).

The condition was supposed to enforce underdamped dynamics, but we no longer think this is necessary (see ref. 52 of the paper https://arxiv.org/pdf/2011.01601.pdf).

I am happy to close this PR.

**Pull request closed without merging**
