### PR TITLE
Bufgfix/mts queue

### PR DESCRIPTION
**Pull request by ceriottm**
when using MTS with multiple force components on the same level, they get computed sequentially.
This creates a queue_mts function that should trigger all calculations at once.

### CODE REVIEW

**Comment by mahrossi** [comment]
@fidanyan -- this should fix the troubles with force components. needs testing also for multiple stress tensors.

**Comment by mahrossi** [comment]
Works with MTS and with SLC (and with MTS+SLC). Missing test for barostats still.

**Comment by ceriottm** [comment]
Can this be merged? We have too many open PR

**Comment by ceriottm** [comment]
@mahrossi can this be merged?

**Comment by ceriottm** [comment]
Approved IRL by @mahrossi

**Pull request merged**
