### PR TITLE
Enh/symlinks

### PR DESCRIPTION
**Pull request by venkatkapil24**
Symlinks for tools

### CODE REVIEW

**Comment by mahrossi** [comment]
Pls black/flake8 :)

**Comment by mahrossi** [comment]
Hi @venkatkapil24 - can you black/flake8 this and then we can merge?

**Comment by mahrossi** [comment]
Hi @venkatkapil24 -- this is going stale. Can you fix things so it is mergeable?

**Comment by venkatkapil24** [comment]
> Hi @venkatkapil24 - can you black/flake8 this and then we can merge?

It is ready.

**Pull request merged**
