### PR TITLE
Fix FFPlumed to work with latest version of PLUMED

### LINKED ISSUE #261: i-pi + plumed: `init_file` is not set by the `ffplumed` parser
Hi I-Pi developers!

I'm having some trouble with i-pi + plumed, which seems to be trivial to resolve.

For example, if I go to `plumed/zundel-metad` example:
https://github.com/i-pi/i-pi/tree/master/examples/plumed/zundel-metad

then run 
```bash
i-pi input.xml
```
for some reason, the `init_file` with the initial xyz structure is not read from the section of xml file within the `ffplumed` section, and it throws the error:

``` python
 # @simulation: Fetchingffplumed
Traceback (most recent call last):
  File "/home/dlbox2/repos/i-pi/bin/i-pi", line 105, in <module>
    main(args[0], options)
  File "/home/dlbox2/repos/i-pi/bin/i-pi", line 48, in main
    simulation = Simulation.load_from_xml(fn_input, request_banner=True, custom_verbosity=options.verbosity)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlbox2/repos/i-pi/ipi/engine/simulation.py", line 94, in load_from_xml
    simulation = input_simulation.fetch()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dlbox2/repos/i-pi/ipi/inputs/simulation.py", line 318, in fetch
    fflist.append(v.fetch())
                  ^^^^^^^^^
  File "/home/dlbox2/repos/i-pi/ipi/inputs/forcefields.py", line 542, in fetch
    init_file=self.init_file.fetch(),
              ^^^^^^^^^^^^^^
AttributeError: 'InputFFPlumed' object has no attribute 'init_file'
```

For now, I'm using a workaround by setting the init filename explicitly within the [`InputFFPlumed` class](https://github.com/i-pi/i-pi/blob/master/ipi/inputs/forcefields.py#L488), but it's not a proper way to resolve the issue:

``` python
class InputFFPlumed(InputForceField):
    fields = {
        "file": (
            InputInitFile,
            {
                "default": input_default(
                    # factory=ipi.engine.initializer.InitFile, kwargs={"value": "./init.xyz", "mode": "xyz"}
                    factory=ipi.engine.initializer.InitFile, kwargs={"mode": "xyz"}
                ),
                "help": "This describes the location to read the reference structure file from.",
            },
        ),
        "plumeddat": (
            InputValue,
            {"dtype": str, "default": "plumed.dat", "help": "The PLUMED input file"},
        ),
        "plumedstep": (
            InputValue,
            {
                "dtype": int,
                "default": 0,
                "help": "The current step counter for PLUMED calls",
            },
        ),
    }

    attribs = {}

    attribs.update(InputForceField.attribs)
    # fields["init_file"] = fields["file"]
    fields.update(InputForceField.fields)

...
```

Probably, some call is missing for updating the `init_file` field somewhere, but I'm not sure where. Do you have any ideas?

### PR DESCRIPTION
**Pull request by ceriottm**
Several  fixes: 
* input parsing (fixes #261 )
* pointer typechecks (needed for compatibility with recent versions of PLUMED)
* a hacky implementation of WTE for single classical trajectories

### CODE REVIEW

**Comment by venkatkapil24** [comment]
are you just waiting for a review?

**Comment by ceriottm** [comment]
yes

**Review by venkatkapil24 — COMMENTED** [review]
approved

**Review by venkatkapil24 — APPROVED** [review]

**Comment by venkatkapil24** [comment]
This should also fix #262

**Pull request merged**
