### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by litman90**
2 minor changes:
- merge repeated folders in examples/features
- add neb to examples/features

### CODE REVIEW

**Comment by litman90** [comment]
This is a free PR as suggested in #270

**Comment by mahrossi** [comment]
Hi there - one thing I would like: please let us not use any capital letters in folder names anywhere? That is in line with the rest of the code and basically all other codes.

**Comment by ceriottm** [comment]
> Hi there - one thing I would like: please let us not use any capital letters in folder names anywhere? That is in line with the rest of the code and basically all other codes.

Also, we should use consistently hyphens and underscores.  right now it's a bit of a mess

**Comment by mahrossi** [comment]
yes, agree. I tried underscores everywhere in the examples folder. any preferences?

**Comment by ceriottm** [comment]
Can we start merging this, in the spirit of updating the examples in steps? I realized I had started doing some more cleanup and now I'm almost certain to find a heap of conflicts.

**Comment by litman90** [comment]
Sure, what is preventing it from being merged at this point?
As far as I can see their actions were taken

-   merge repeated folders in examples/features
-   add neb to examples/features and add some warning regarding usage
-  renaming here and there

**Review by ceriottm — APPROVED** [review]
All looks good. Will immediately open another branch and PR so we can keep iterating

**Pull request merged**
