### PR TITLE
add LICENSE.md file before v3.0 release

### PR DESCRIPTION
**Pull request by litman90**
Add a LICENSE.md file explaining that the code within the driver folder is published within the MIT license and the rest under the GPL license.
@ceriottm, if you want to change the licence, now would be a good time. Otherwise please merge this.

### CODE REVIEW

**Review by ceriottm — DISMISSED** [review]

**Review by ceriottm — COMMENTED** [review]
OK Sorry wait a sec, why do we need this in addition to the existing license files?

**Comment by litman90** [comment]
Because, as far as I can tell, it is not specified clearly what a GPL licence, is and what's MIT licence.

**Comment by litman90** [comment]
and I thought this was a good place to make it explicit.
Should I merge, or do you prefer doing it in differently?

**Comment by ceriottm** [comment]
OK so the idea, that was discussed and agreed upon ages ago, is that the whole project is DUAL licensed - so one can pick whatever license suits them best.

**Comment by mahrossi** [comment]
Sorry I missed this - yes, I confirm we agreed that all of it should be dual-licensed. I heard criticisms about this from external sources. But I am not sure we can change that now.

**Comment by litman90** [comment]
As the owners of the code, if we all agree, we can change it ( I mean legally speaking) .
We can discuss it quickly tomorrow.

**Comment by litman90** [comment]
Adding LICENSE.md  file as discussed in the last coordinator's meeting.

**Pull request merged**
