### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ianhbell**
The folders must have moved, README out of date.

### CODE REVIEW

**Comment by ceriottm** [comment]
Thanks a lot for your contribution. Even these small fixes help keep the code in good shape. @litman90 looks like there are problems with the CI, do you have a clue of what the problem might be?

**Comment by litman90** [comment]
I agree with @ceriottm. Thanks for your contribution.
Let me check what is going on with the CI

**Comment by litman90** [comment]
('git hub actions' is down ... https://www.githubstatus.com/) so I can't check if my fixes to the CI are working XD

**Comment by ianhbell** [comment]
Thanks folks, nice work on this project!

**Pull request merged**
