### PR TITLE
Examples with zero errors

### PR DESCRIPTION
**Pull request by ceriottm**
The purpose of this PR is to make sure that we are back into a state where ALL examples run through the extended tests - except perhaps those that require special libraries on the python side, like PLUMED.

### CODE REVIEW

**Comment by mahrossi** [comment]
I think all tests run now -- at least they ran yesterday night. This could be merged.

**Comment by ceriottm** [comment]
Do examples all run for real? Also the idea here was to remove the "do not run this test" file, and make sure that *all* examples run, is that the case?

**Comment by venkatkapil24** [comment]
perhaps I am wrong, but this shows just a small change in a readme. I say we close this and pick up the new branch.

**Review by venkatkapil24 — COMMENTED** [review]
these changes will reflect in the new PR #245

**Comment by venkatkapil24** [comment]
I am closing this. @ceriottm

**Pull request closed without merging**
