### PR TITLE
Hopefully this is the time this is fixed for good....

### PR DESCRIPTION
**Pull request by ceriottm**
Fixed problem in transfer_forces with multiple beads, and also explained in a lengthy comment what is the problem and rationale for setting ForceComponent q values in transfer_forces

### CODE REVIEW

**Comment by mahrossi** [comment]
Hi there, we had more discussions in the Slack channel. @ceriottm, Yair has tested the new implementation in his instanton branch BUT I don't think we tested the "no-op" contraction explicitly (did you? if so let us know) and also just as a sanity check, the relaxation benchmarks again. Shall we do it tomorrow and merge?

**Comment by ceriottm** [comment]
Didn't check thoroughly. OK to merge tomorrow!

**Comment by ceriottm** [comment]
One thing - unrelated but that we can bundle with this PR.
examples/regtest/lammps/h2o-geop-fixatoms
is not structured as a proper regtest - there's a bunch of scripts, README,
etc.
it is kind of annoying to have it there as it inevitably fails when you run
the folder as a regtest.
Can it be fixed or moved?

**Comment by mahrossi** [comment]
this is from @fidanyan and he is sick at the moment. I can't deal with it today, sorry.

**Comment by mahrossi** [comment]
Can we open a separate PR for that so I can do it in my fork?

**Comment by mahrossi** [comment]
I have tested other geometry optimizations and they have passed. I will now merge this and open the other PR to fix the regtest  that should be merged tomorrow.

**Pull request merged**
