### PR TITLE
Examples restructured

### PR DESCRIPTION
**Pull request by litman90**
Only minor changes.
Let's try to keep this updated to master =)

### CODE REVIEW

**Comment by mahrossi** [comment]
Why does this have 110 commits? This is looking a bit weird. That branch had been merged.

**Comment by litman90** [comment]
If I look at 'files changed here' everything looks fine.

Regarding the coming count, I think it is because it was squashed before merging. We can kill this branch and open a new one if you think it would be better. Otherwise, we can merge this and continue using this branch for upcoming updates on this front (which we all agree are still needed).

**Comment by ceriottm** [comment]
I think we should probably create a new branch, otherwise we'll get a mess. If you have done any changes, I let you create a new branch from master, move over your changes, and then open a new PR from the new branch. I think moving forward we should delete the branch when we merge, and recreate it if we want to keep the work going.

**Comment by litman90** [comment]
Agree. I will close, delete this branch, and create a fresh PR.

**Pull request closed without merging**
