### PR TITLE
Set CI's os to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by litman90**
Let's see what happens

### CODE REVIEW

**Comment by litman90** [comment]
This PR modifies the os where the CI runs the tests.
Before it was ubuntu-latest and now it is 18.04. 
It seems the more sensible thing to do a the moment.

**Comment by litman90** [comment]
The pytest-examples are not running, I should fix this before this PR can be merged

**Comment by litman90** [comment]
Now we are fine to merge.
@mahrossi could you review it?

**Review by ceriottm — APPROVED** [review]
Seems the most sensible stop-gap measure so we can merge the other PRs without being distracted by these regtest errors

**Pull request merged**
