### PR TITLE
Clean up and improve constraints code

### PR DESCRIPTION
**Pull request by ceriottm**
This is a PR to complete the work from #224 , that was merged to address the most urgent bugfixes. 
Constraints are implemented but half-working and need some love to be fully usable.

### CODE REVIEW

**Comment by ceriottm** [comment]
See also #221 and tagging @nickgerrits and @MatthiasSachs

**Comment by mahrossi** [comment]
This looks like a pretty clean and clear PR to me. 

Are there regtests for the constrained dyn? I could not find them. Wouldn't it be good to add them here?

**Comment by MatthiasSachs** [comment]
Apologies for remaining silent throughout the whole process so far. 

One (very late) comment regarding the occasional occurrence of singular Gramians, which @nickgerrits raised. I agree that having additional safeguards to deal with singular Gramians would be good. Having said that, I also briefly discussed this with Ben Leimkuhler at some point and he mentioned [this article](https://onlinelibrary.wiley.com/doi/epdf/10.1002/jcc.540161003?saml_referrer=), according to which degenerated Gramian only occur in the presence of "dependent constraints", e.g., a collection of distance/bond constraints that form a ring. 

I will be a bit tied up with teaching in the weeks to come, but if there are things that would need to be urgently done, please let me know!

**Comment by mahrossi** [comment]
Hi, is this ready? It does not seem like previous comments were addressed.

**Pull request closed without merging**
