### PR TITLE
Update sGDML force field dependencies

### PR DESCRIPTION
**Pull request by sauceda**
(Version py2) Update sGDML dependencies, add some useful flags regarding the units, and parallelization of the predictor function.

Also, the ffsgdml example section was restructured and a README file was added. The previous models were updated since they were from an outdated sGDML version.

### CODE REVIEW

**Comment by mahrossi** [comment]
Hello, we are not accepting PRs to the python2 version anymore. Could you do it in py3 only?

**Comment by venkatkapil24** [comment]
@mahrossi: This discussion had started a while back, and I think it should be merged. And I agree that it should be the last thing getting merged into the  py2 branch. I will take a look at it today.

**Comment by venkatkapil24** [comment]
@sauceda: It seems that the models are not part of the repo. Can you add them super quick and then we can merge this ?

**Comment by sauceda** [comment]
@venkatkapil24 OK, I have added the missing files.

**Comment by venkatkapil24** [comment]
@sauceda: Perfect ! Can you also fix the bug that I pointed out ?

**Comment by sauceda** [comment]
@venkatkapil24 Yes, done.

**Comment by venkatkapil24** [comment]
There seems to be a problem. I get the following error:

Traceback (most recent call last):
  File "/Users/venkatkapil/bin/i-pi", line 105, in <module>
    main(args[0], options)
  File "/Users/venkatkapil/bin/i-pi", line 48, in main
    simulation = Simulation.load_from_xml(fn_input, request_banner=True, custom_verbosity=options.verbosity)
  File "/Users/venkatkapil/source/i-pi/ipi/engine/simulation.py", line 92, in load_from_xml
    simulation = input_simulation.fetch()
  File "/Users/venkatkapil/source/i-pi/ipi/inputs/simulation.py", line 213, in fetch
    fflist.append(v.fetch())
  File "/Users/venkatkapil/source/i-pi/ipi/inputs/forcefields.py", line 400, in fetch
    return FFsGDML(sGDML_model=self.sGDML_model.fetch(), name=self.name.fetch(), latency=self.latency.fetch(), dopbc=self.pbc.fetch(), threaded=self.threaded.fetch())
  File "/Users/venkatkapil/source/i-pi/ipi/engine/forcefields.py", line 824, in __init__
    self.predictor.prepare_parallel(n_bulk=1)
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/site-packages/sgdml/predict.py", line 755, in prepare_parallel
    gps = n_bulk * n_reps / timeit.timeit(_dummy_predict, number=n_reps)
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/timeit.py", line 100, in inner
    _func()
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/site-packages/sgdml/predict.py", line 698, in _dummy_predict
    self.predict(r_dummy)
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/site-packages/sgdml/predict.py", line 1083, in predict
    E_F[i, :] = _predict_wo_wkr_starts_stops()
  File "/Users/venkatkapil/anaconda2/envs/py2.7/lib/python2.7/site-packages/sgdml/predict.py", line 218, in _predict_wkr
    np.dot(F, r_d_desc, out=out[1:])
TypeError: dep_dot() got an unexpected keyword argument 'out'

I am using version 0.4.3 of sgdml. Is that okay ?

**Comment by sauceda** [comment]
Ok, not sure why sometimes this happens, but we are working on fixing this bug. It only needs to change line 218: np.dot(F, r_d_desc, out=out[1:]) ---> out[1:] = np.dot(F, r_d_desc). I'll let you know when this is fixed in the sGDML github.

**Comment by venkatkapil24** [comment]
@sauceda: Are you able to reproduce this bug ? Which version of sgdml are you using ?

**Comment by sauceda** [comment]
Yes, it looks like there was a problem with numpy. Now, Stefan fixed this bug in the developer version of the code. This fix will be added soon to the stable release of the sGDML package. In the meantime, for this version of i-PI it is better to use the developer version of sGDML, I tried and it works. Just run:

$ git clone https://github.com/stefanch/sGDML.git
$ cd sGDML
$ pip2 install -e .

**Comment by venkatkapil24** [comment]
Then it would be best to modify the following lines and add the appropriate instructions for installing sGDML

        # --- Load sGDML package ---
        try:
            from sgdml.predict import GDMLPredict
            from sgdml import __version__
            info(" @ForceField: Using sGDML version " + __version__, verbosity.low)
        except:
            raise ValueError("ERROR: sGDML package not located. Install it via: pip install sgdml")

I can then test the branch and merge.

**Comment by sauceda** [comment]
Ok, done it.

**Pull request merged**
