### PR TITLE
Carry on and display more meaningful errors for py driver

### PR DESCRIPTION
**Pull request by ceriottm**
When importing one of the PES files fails the python driver currently dies with a cryptic message. This small PR lets the driver continue, and prints more meaningful error messages that can help debug the faulty PES.

### CODE REVIEW

**Comment by ceriottm** [comment]
@DavideTisi  I think this could have helped you today.

**Comment by ceriottm** [comment]
> So, just for my understanding: then if the driver cannot load the pes it will continue doing something anyways? Isn't that dangerous?

If it cannot load ONE PES, it will still be able to run with ANOTHER PES. Without this fix, if there's a problem importing say MACE, it won't be able to run with the harmonic PES - and it will not even tell you clearly it failed with loading MACE, just that it couldn't parse the pes module.

**Comment by mahrossi** [comment]
ah I see, that is clear - I understand. but if it was asked to use in particular the PES that it could not load, then it will just refuse to do something.

**Comment by ceriottm** [comment]
> ah I see, that is clear - I understand. but if it was asked to use in particular the PES that it could not load, then it will just refuse to do something.

yes it will give another error further down

**Comment by ceriottm** [comment]
so can I merge this (and the ASE fix that I had branched from this one?)?

**Review by DavideTisi — APPROVED** [review]

**Comment by DavideTisi** [comment]
for me you can merge

**Pull request merged**
